export const DSA5GodsMenuConfig = {
    godIconMap: {
        "Angrosch": "Angrosch.png",
        "Aves": "Aves.png",
        "Boron": "Boron(PuninerRitus).png",
        "Brazoragh": "Brazoragh.png",
        "Efferd": "Efferd.png",
        "Firun": "Firun.png",
        "Hesinde": "Hesinde.png",
        "Himmelswölfe": "Himmelswölfe.png",
        "Ifirn": "Ifirn.png",
        "Ingerimm": "Ingerimm.png",
        "Kamaluq": "Kamaluq.png",
        "Kor": "Kor.png",
        "Levthan": "Levthan.png",
        "Mada": "Mada.png",
        "Marbo": "Marbo.png",
        "Mokoscha": "Mokoscha.png",
        "Namenloser": "Namenloser.png",
        "Nandus": "Nandus.png",
        "Numinoru": "Numinoru.png",
        "Peraine": "Peraine.png",
        "Phex": "Phex.png",
        "Praios": "Praios.png",
        "Rahja": "Rahja.png",
        "Rastullah": "Rastullah.png",
        "Rondra": "Rondra.png",
        "Satuaria": "Satuaria.png",
        "Shinxir": "Shinxir.png",
        "Simia": "Simia.png",
        "Swafnir": "Swafnir.png",
        "Tairach": "Tairach.png",
        "Travia": "Travia.png",
        "Tsa": "Tsa.png",
        "Ucuri": "Ucuri.png",
        "Xeledon": "Xeledon.png"
    },
    demonIconMap: {
        "Agrimoth": "Agrimoth.png",
        "Amazeroth": "Amazeroth.png",
        "Aphasmayra": "Aphasmayra.png",
        "Aphestadil": "Aphestadil.png",
        "Asfaloth": "Asfaloth.png",
        "Belhalhar": "Belhalhar.png",
        "Belkelel": "Belkelel.png",
        "Blakharaz": "Blakharaz.png",
        "Charyptoroth": "Charyptoroth.png",
        "Heskatet": "Heskatet.png",
        "Lolgramoth": "Lolgramoth.png",
        "Mishkara": "Mishkara.png",
        "Nagrach": "Nagrach.png",
        "Tasfarel": "Tasfarelel.png",
        "Thargunitoth": "Thargunitoth.png"
    },
    diceIconMap: {
        "Agrimoth": "Agrimoth.png",
        "Amazeroth": "Amazeroth.png",
        "Angrosch": "Angrosch.png",
        "Aphasmayra": "Aphasmayra.png",
        "Aphestadil": "Aphestadil.png",
        "Asfaloth": "Asfaloth.png",
        "Aves": "Aves.png",
        "Belhalhar": "Belhalhar.png",
        "Belkelel": "Belkelel.png",
        "Blakharaz": "Blakharaz.png",
        "Boron": "Boron(PuninerRitus).png",
        "Brazoragh": "Brazoragh.png",
        "Charyptoroth": "Charyptoroth.png",
        "Efferd": "Efferd.png",
        "Firun": "Firun.png",
        "Hesinde": "Hesinde.png",
        "Heskatet": "Heskatet.png",
        "Himmelswölfe": "Himmelswoelfe.png",
        "Ifirn": "Ifirn.png",
        "Ingerimm": "Ingerimm.png",
        "Kamaluq": "Kamaluq.png",
        "Kor": "Kor.png",
        "Levthan": "Levthan.png",
        "Lolgramoth": "Lolgramoth.png",
        "Mada": "Mada.png",
        "Marbo": "Marbo.png",
        "Mishkara": "Mishkara.png",
        "Mokoscha": "Mokoscha.png",
        "Nagrach": "Nagrach.png",
        "Namenloser": "Namenloser.png",
        "Nandus": "Nandus.png",
        "Numinoru": "Numinoru.png",
        "Peraine": "Peraine.png",
        "Phex": "Phex.png",
        "Praios": "Praios.png",
        "Rahja": "Rahja.png",
        "Rastullah": "Rastullah.png",
        "Rondra": "Rondra.png",
        "Satuaria": "Satuaria.png",
        "Shinxir": "Shinxir.png",
        "Simia": "Simia.png",
        "Swafnir": "Swafnir.png",
        "Tairach": "Tairach.png",
        "Tasfarel": "Tasfarelel.png",
        "Thargunitoth": "Thargunitoth.png",
        "Travia": "Travia.png",
        "Tsa": "Tsa.png",
        "Ucuri": "Ucuri.png",
        "Xeledon": "Xeledon.png"
    },
    godListNames: [
        "Angrosch", "Aves", "Boron", "Brazoragh", "Efferd", "Firun", "Hesinde", 
        "Himmelswölfe", "Ifirn", "Ingerimm", "Kamaluq", "Kor", "Levthan", "Mada", 
        "Marbo", "Mokoscha", "Namenloser", "Nandus", "Numinoru", "Peraine", "Phex", 
        "Praios", "Rahja", "Rastullah", "Rondra", "Satuaria", "Shinxir", "Simia", 
        "Swafnir", "Tairach", "Travia", "Tsa", "Ucuri", "Xeledon"
    ],
    demonListNames: [
        "Agrimoth", "Amazeroth", "Aphasmayra", "Aphestadil", "Asfaloth", "Belhalhar", 
        "Belkelel", "Blakharaz", "Charyptoroth", "Heskatet", "Lolgramoth", "Mishkara", 
        "Nagrach", "Tasfarel", "Thargunitoth"
    ],
    qsandreroll: {
        "Agrimoth": ["Talent.Fliegen", "Talent.Holzbearbeitung", "Talent.Metallbearbeitung", "Talent.Pflanzenkunde", "Talent.Steinbearbeitung"],
        "Aphasmayra": ["Talent.Betoeren", "Talent.Klettern", "Talent.Orientierung", "Talent.Verbergen"],
        "Aphestadil": ["Talent.Einschuechtern", "Talent.Sinnesschaerfe", "Talent.Zechen"],
        "Belkelel": ["Talent.Betoeren", "Talent.Einschuechtern", "Talent.Fesseln", "Talent.Selbstbeherrschung", "Talent.Zechen"],
        "Heskatet": ["Talent.SagenUndLegenden", "Talent.Sinnesschaerfe", "Talent.Sphaerenkunde"],
        "Tasfarel": ["Talent.Handel", "Talent.Ueberreden", "Talent.Verbergen"],
        "Thargunitoth": ["Talent.HeilkundeSeele", "Talent.Selbstbeherrschung", "Talent.Willenskraft"],
        "Angrosch": ["Talent.Holzbearbeitung", "Talent.Kraftakt", "Talent.Mechanik", "Talent.Metallbearbeitung", "Talent.Steinbearbeitung", "Talent.Zechen"],
        "Boron": ["Talent.HeilkundeSeele", "Talent.Menschenkenntnis", "Talent.Willenskraft"],
        "Efferd": ["Talent.BooteUndSchiffe", "Talent.FischenUndAngeln", "Talent.Koerperbeherrschung", "Talent.Schwimmen"],
        "Firun": ["Talent.Faehrtensuchen", "Talent.Orientierung", "Talent.Tierkunde", "Talent.Wildnisleben"],
        "Hesinde": ["Talent.Geschichtswissen", "Talent.GoetterUndKulte", "Talent.Magiekunde"],
        "Himmelswölfe": ["Talent.Faehrtensuchen", "Talent.Koerperbeherrschung", "Talent.Wildnisleben"],
        "Ingerimm": ["Talent.Holzbearbeitung", "Talent.Kraftakt", "Talent.Mechanik", "Talent.Lederbearbeitung", "Talent.Metallbearbeitung", "Talent.Stoffbearbeitung"],
        "Kamaluq": ["Talent.Einschuechtern", "Talent.Klettern", "Talent.Tierkunde", "Talent.Wildnisleben"],
        "Levthan": ["Talent.Betoeren", "Talent.Kraftakt", "Talent.Willenskraft", "Talent.Zechen"],
        "Namenloser": ["Talent.BekehrenUndUeberzeugen", "Talent.Menschenkenntnis", "Talent.Selbstbeherrschung", "Talent.Willenskraft"],
        "Numinoru": ["Talent.FischenUndAngeln", "Talent.Schwimmen", "Talent.Willenskraft"],
        "Peraine": ["Talent.HeilkundeGift", "Talent.HeilkundeKrankheiten", "Talent.HeilkundeWunden", "Talent.Pflanzenkunde"],
        "Rahja": ["Talent.Betoeren", "Talent.Etikette", "Talent.Reiten", "Talent.Tanzen", "Talent.Zechen"],
        "Rastullah": ["Talent.Orientierung", "Talent.Rechtskunde", "Talent.Reiten", "Talent.Willenskraft"],
        "Satuaria": ["Talent.Betoeren", "Talent.Fliegen", "Talent.HeilkundeGift", "Talent.HeilkundeKrankheiten", "Talent.Lebensmittelbearbeitung"],
        "Swafnir": ["Talent.BooteUndSchiffe", "Talent.FischenUndAngeln", "Talent.Koerperbeherrschung", "Talent.Schwimmen"],
        "Tairach": ["Talent.Magiekunde", "Talent.Sternkunde", "Talent.Willenskraft"],
        "Ucuri": ["Talent.BekehrenUndUeberzeugen", "Talent.Rechtskunde", "Talent.Sinnesschaerfe"]
    },
    extra: {
        "Aves": ["ALL"],
        "Phex": ["ALL"]
    }
};
